FROM python:3.7.5
COPY . /data
WORKDIR /data
EXPOSE 40000

RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen es_ES.UTF-8
#ENV LANG es_ES.UTF-8  
#ENV LANGUAGE es_ES:es  
#ENV LC_ALL es_ES.UTF-8
#ENV PYTHONENCODING es_ES.UTF-8

RUN pip install -r requirements.txt
RUN python -m spacy download es
RUN python -m spacy download en
RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader stopwords